import { PageHero, Section, SiteLink } from '../kit';
import { portalHref } from '../../config/hosts';
import { PRICING } from '../prices';
import { CLOUD_ADDON, PLANS, SETUP_FEE, money } from '../../domain/plans';
export function PricingPage(){return <>
<PageHero eyebrow="Plans & setup" title="Start with what you have." lede="Every plan tracks everything. Plans differ by crew size and whether photos and paperwork are saved online. Beta pricing."/>
<Section><div className="plan-options">
{PLANS.map(p=><article key={p.id} className="plan-option"><h2>{p.name}</h2><p className="plan-price">${p.monthly}<span> / warehouse / month</span></p><p>{p.blurb}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}<li>Ongoing remote support</li></ul><SiteLink to="start" className={`site-btn${p.id==='plus'?' primary':''}`}>Find your plan</SiteLink></article>)}
</div><p className="plan-note">Every plan starts with a free {PRICING.pilotDays}-day trial when you set it up yourself. Not sure which fits? The 2-minute survey recommends one.</p></Section>
<Section title="Add-on"><div className="plan-options"><article className="plan-option"><h2>{CLOUD_ADDON.name}</h2><p className="plan-price">+{money(CLOUD_ADDON.monthly)}<span> / warehouse / month</span></p><p>Photos of damage, delivery papers and signed receipts saved with every record and backed up online. Without it, paper records are included at no extra cost.</p></article></div></Section><Section tone="surface" title="Want it done for you?"><div className="plan-options"><article className="plan-option"><h2>Tech setup</h2><p className="plan-price">${SETUP_FEE.small}<span> one time, ${SETUP_FEE.large} for larger buildings</span></p><p>A Wherehouse tech comes to you, builds your zones and spots, hangs the labels, loads your items and trains your crew. Your first month is included; after that, your plan bills monthly until you cancel.</p><ul><li>First month of your plan included</li><li>Within about an hour of Charleston, SC</li><li>Farther away? Contact us and we’ll work something out</li></ul><SiteLink to="start" className="site-btn primary">Check your zip code</SiteLink></article></div></Section>
<Section tone="surface" title="What’s included"><div className="buyer-table-wrap"><table className="buyer-table"><thead><tr><th>Included</th><th>Use your equipment</th><th>Equipment & setup</th></tr></thead><tbody>
{['Shared records, photos and movement history','Phone scanning and printed labels','Manager and employee accounts','Remote support for the whole app'].map(t=><tr key={t}><th>{t}</th><td>Yes</td><td>Yes</td></tr>)}
<tr><th>Printer, labels and hardware setup</th><td>Use your own; we help remotely</td><td>Included in your agreed quote</td></tr><tr><th>On-site visit</th><td>Available by arrangement</td><td>Can be included in your quote</td></tr>
</tbody></table></div></Section>
<Section narrow title={`Try it free for ${PRICING.pilotDays} days.`}><p>Answer a few questions and we’ll recommend a setup for how you work, then start your free trial. No card and no automatic charge. Rather see it in your building first? Book a free walkthrough.</p><div className="site-hero-actions"><SiteLink to="start" className="site-btn primary">Start your free trial</SiteLink><SiteLink to="contact" className="site-btn ghost">Book a free walkthrough</SiteLink></div><a className="site-link" href={portalHref('?demo=1#signin')}>Browse the sample warehouse →</a></Section>
</>;}
