import { test, expect } from '@playwright/test';
import { signInAs } from './helpers';

test('choosing "Big single items" renames pallets to items and hides jobs', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 });
  await signInAs(page, 'supervisor');
  await page.goto('/?demo=1#overview');
  await page.getByRole('button', { name: 'Warehouse settings' }).click();
  const setup = page.getByTestId('setup-setting');
  await setup.getByRole('radio', { name: /Big single items/ }).click();
  await setup.getByRole('button', { name: 'Save setup' }).click();
  await expect(setup).toContainText('Saved.');
  await page.keyboard.press('Escape');
  const nav = page.locator('.sidebar');
  await expect(nav.getByRole('button', { name: /Item types/ })).toBeVisible();
  await expect(nav.getByRole('button', { name: /^Jobs/ })).toHaveCount(0);
  await page.goto('/?demo=1#move');
  await expect(page.locator('body')).not.toContainText(/\bpallet/i);
});

test('crew get a simple Find, Move, Add screen, with the full dashboard a tap away', async ({ page }) => {
  await signInAs(page, 'operator');
  await page.goto('/?demo=1#overview');
  const home = page.getByTestId('crew-home');
  await expect(home.locator('.crew-tile')).toHaveCount(3);
  await home.getByRole('button', { name: 'Move' }).click();
  await expect(page).toHaveURL(/#move/);
  await page.goto('/?demo=1#overview');
  await page.getByRole('button', { name: 'Show the full dashboard' }).click();
  await expect(page.locator('.warehouse-metrics')).toBeVisible();
});

test('the website survey checks the printer, recommends a setup and leads to the free trial', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/?demo=1#start');
  const s = page.getByTestId('setup-survey');
  await s.getByRole('button', { name: 'Start', exact: true }).click();
  await s.getByRole('radio', { name: /Parts and boxes on shelves/ }).click();
  await s.getByRole('radio', { name: /100 to 1,000/ }).click();
  await expect(s).toContainText('We need to know this to create your storage zones');
  await expect(s.getByRole('checkbox', { name: /Pallet racks/ })).toHaveCount(0);
  await s.getByRole('button', { name: /more storage options/ }).click();
  await expect(s.getByRole('checkbox', { name: /Sheds or outbuildings/ })).toBeVisible();
  await s.getByRole('checkbox', { name: /Shelves and bins/ }).click();
  await s.getByRole('button', { name: 'Continue' }).click();
  await s.getByRole('radio', { name: 'Shelves and bins: 2 to 5' }).click();
  await s.getByRole('button', { name: 'Continue' }).click();
  await s.getByRole('radio', { name: /Many things in one spot/ }).click();
  await s.getByRole('radio', { name: /2 to 5/ }).click();
  await s.getByRole('radio', { name: /For orders/ }).click();
  await s.getByRole('radio', { name: /^Yes/ }).click();
  await s.getByRole('radio', { name: /Handheld label maker/ }).click();
  await expect(s.getByTestId('printer-verdict')).toContainText('Not a fit');
  await s.getByRole('button', { name: 'Continue' }).click();
  await s.getByRole('radio', { name: /Phone camera/ }).click();
  await s.getByRole('radio', { name: /No, paper is fine/ }).click();
  await s.getByRole('radio', { name: /^No$/ }).click();
  await s.getByRole('textbox').fill('29403');
  await s.getByRole('button', { name: 'Continue' }).click();
  const results = s.getByTestId('survey-results');
  await expect(results).toContainText('Items');
  await expect(results).toContainText('Avery 5160');
  await expect(results).toContainText('zones A to C');
  await expect(results).toContainText('This is a starting point');
  await results.getByRole('button', { name: /Start your free trial/ }).click();
  await expect(page).toHaveURL(/#signin/);
  expect(await page.evaluate(() => localStorage.getItem('pl.survey'))).toContain('shelves');
});

test('a manager can retake the survey in the portal and apply it', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width: 1280, height: 900 });
  await signInAs(page, 'supervisor');
  await page.goto('/?demo=1#overview');
  await page.getByRole('button', { name: 'Warehouse settings' }).click();
  await page.getByRole('button', { name: 'Retake the setup survey' }).click();
  const s = page.getByTestId('setup-survey');
  await s.getByRole('button', { name: 'Start', exact: true }).click();
  await s.getByRole('radio', { name: /Long goods/ }).click();
  await s.getByRole('radio', { name: /Under 100/ }).click();
  await s.getByRole('checkbox', { name: /Long-goods racks/ }).click();
  await s.getByRole('button', { name: 'Continue' }).click();
  await s.getByRole('radio', { name: 'Long-goods racks: 1' }).click();
  await s.getByRole('button', { name: 'Continue' }).click();
  await s.getByRole('radio', { name: /One thing per spot/ }).click();
  await s.getByRole('radio', { name: /Just me/ }).click();
  await s.getByRole('radio', { name: /^No/ }).first().click();
  await s.getByRole('radio', { name: /No, not yet/ }).click();
  await s.getByRole('radio', { name: /Phone camera/ }).click();
  await s.getByRole('radio', { name: /^No$/ }).click();
  await s.getByTestId('survey-results').getByRole('button', { name: /Use this setup/ }).click();
  await expect(s).toHaveCount(0);
  await expect(page.getByTestId('setup-setting')).toContainText('Bundles');
});

test('the plan survey recommends a plan, checks the zip for a tech visit and offers the trial', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const answer = async (zip: string) => {
    await page.goto('about:blank');
    await page.goto('/?demo=1#start');
    const s = page.getByTestId('setup-survey');
    await s.getByRole('button', { name: 'Start', exact: true }).click();
    await s.getByRole('radio', { name: /Big single items/ }).click();
    await s.getByRole('radio', { name: /Under 100/ }).click();
    await s.getByRole('checkbox', { name: /Floor space/ }).click();
    await s.getByRole('button', { name: 'Continue' }).click();
    await s.getByRole('radio', { name: 'Floor space: 1' }).click();
    await s.getByRole('button', { name: 'Continue' }).click();
    await s.getByRole('radio', { name: /One thing per spot/ }).click();
    await s.getByRole('radio', { name: /6 to 20/ }).click();
    await s.getByRole('radio', { name: /^No/ }).first().click();
    await s.getByRole('radio', { name: /No, not yet/ }).click();
    await s.getByRole('radio', { name: /Phone camera/ }).click();
    await s.getByRole('radio', { name: /Yes, save them online/ }).click();
    await s.getByRole('radio', { name: /^No$/ }).click();
    await s.getByRole('textbox').fill(zip);
    await s.getByRole('button', { name: 'Continue' }).click();
    return s.getByTestId('plan-choice');
  };
  let plan = await answer('29464');
  await expect(plan).toContainText('Plus');
  await expect(plan.getByTestId('way-tech')).toContainText('We cover 29464');
  await plan.getByRole('button', { name: /Pay now/ }).click();
  await expect(plan).toContainText('Online payment isn’t switched on yet');
  await expect(plan.getByTestId('way-diy')).toContainText('difficult process');
  plan = await answer('90210');
  await expect(plan.getByTestId('way-tech')).toContainText('isn’t available in 90210');
  await expect(plan.getByTestId('way-tech').getByRole('link', { name: /Contact us/ })).toHaveAttribute('href', /^mailto:/);
});
