import {testSignup} from './signup.mjs';
import './local-only.mjs';
import {issueKey,licenseStore} from './keys.mjs';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { randomUUID } from 'node:crypto';
import { initializeApp, deleteApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, signInWithEmailAndPassword, signOut } from 'firebase/auth';
import { getFirestore, connectFirestoreEmulator, doc, getDoc, setDoc, collection, getDocs, onSnapshot, query, limit } from 'firebase/firestore';
import { getFunctions, connectFunctionsEmulator, httpsCallable } from 'firebase/functions';
import { getStorage, connectStorageEmulator, ref, uploadBytes, getBytes } from 'firebase/storage';
const require=createRequire(new URL('../../firebase/functions/package.json',import.meta.url));
process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';
const {initializeApp:adminInit}=require('firebase-admin/app');const {getAuth:adminAuth}=require('firebase-admin/auth');
adminInit({projectId:'demo-wherehouse'});
const apps=[];const password='Warehouse-test-123!';const suffix=Date.now();
async function client(label,verified=true){
 const user=await adminAuth().createUser({email:`${label}-${suffix}@example.com`,password,emailVerified:verified,displayName:label});
 const app=initializeApp({apiKey:'demo-key',projectId:'demo-wherehouse',authDomain:'demo-wherehouse.firebaseapp.com',storageBucket:'demo-wherehouse.appspot.com'},label);apps.push(app);
 const auth=getAuth(app);connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});await signInWithEmailAndPassword(auth,user.email,password);
 const db=getFirestore(app);connectFirestoreEmulator(db,'127.0.0.1',8080);
 const fn=getFunctions(app,'us-east1');connectFunctionsEmulator(fn,'127.0.0.1',5001);
 const storage=getStorage(app);connectStorageEmulator(storage,'127.0.0.1',9199);
 return {user,auth,db,storage,call:async(name,data)=>(await httpsCallable(fn,name)(data)).data};
}
let checks=0;const ok=label=>{checks++;console.log(`PASS ${label}`);};
try {
 await testSignup();
 const owner=await client('owner'),operator=await client('operator'),outsider=await client('outsider'),viewer=await client('viewer'),unverified=await client('unverified',false);
 await assert.rejects(unverified.call('createWarehouse',{name:'Blocked'}));ok('unverified email cannot create warehouse');
 await assert.rejects(owner.call('createWarehouse',{name:'Missing key'}));ok('verified account cannot create warehouse without usage key');
 const wrongKey=await issueKey(outsider.user.email);await assert.rejects(owner.call('createWarehouse',{name:'Wrong account',usageKey:wrongKey}));ok('usage key is bound to the authorized account');
 const ownerKey=await issueKey(owner.user.email);
 const {workspaceId:ws}=await owner.call('createWarehouse',{name:'Test receiving warehouse',timezone:'America/New_York',usageKey:ownerKey});
 await assert.rejects(owner.call('createWarehouse',{name:'Reused key',usageKey:ownerKey}));ok('activation key cannot be reused');
 assert.equal((await owner.call('createWarehouse',{name:'Retry'})).workspaceId,ws);ok('warehouse creation is idempotent');
 const {workspaceId:otherWs}=await outsider.call('createWarehouse',{name:'Other warehouse',usageKey:wrongKey});
 const envelope=(kind,payload,more={})=>({schema_version:1,command_id:randomUUID(),workspace_id:ws,kind,payload,...more});
 const send=(who,kind,payload,more)=>who.call('command',envelope(kind,payload,more));
 for(const [person,role] of [[operator,'OPERATOR'],[viewer,'VIEWER']]) assert.equal((await send(owner,'invite_member',{name:person.user.displayName,email:person.user.email,role})).ok,true);
 await assert.rejects(getDoc(doc(outsider.db,'workspaces',ws)));await assert.rejects(getDoc(doc(owner.db,'workspaces',otherWs)));ok('warehouse isolation blocks cross-account reads');
 await assert.rejects(setDoc(doc(owner.db,'workspaces',ws,'pallets','fake'),{state:'STORED'}));ok('even owners cannot bypass server writes');
 const job=await send(owner,'create_job',{code:'J-214',name:'School renovation'});assert.equal(job.ok,true);
 const a=await send(owner,'create_location',{code:'A-01-01',kind:'RACK'}),b=await send(owner,'create_location',{code:'A-01-02',kind:'RACK'});assert.equal(a.ok,true);assert.equal(b.ok,true);
 const cmd=envelope('receive',{job_id:job.target_id,description:'Lighting fixtures'});
 const received=await owner.call('command',cmd);assert.equal(received.ok,true,JSON.stringify(received));
 const replay=await owner.call('command',cmd);assert.equal(replay.current_state.id,received.current_state.id);
 assert.equal((await getDocs(query(collection(owner.db,'workspaces',ws,'pallets'),limit(100)))).size,1);ok('replayed receive creates exactly one pallet');
 const changed=await owner.call('command',{...cmd,payload:{...cmd.payload,description:'Different'}});assert.equal(changed.code,'COMMAND_KEY_REUSED');ok('request ID cannot be reused for another action');
 const denied=await send(viewer,'receive',{job_id:job.target_id,description:'Not allowed'});assert.equal(denied.code,'FORBIDDEN');ok('viewer cannot receive');
 const p=received.current_state;const version={pallet_id:p.id,expected_version:p.version};
 const race=await Promise.all([send(owner,'place',{location_id:a.target_id},version),send(operator,'place',{location_id:b.target_id},version)]);
 assert.equal(race.filter(r=>r.ok).length,1);assert.equal(race.filter(r=>r.code==='VERSION_CONFLICT').length,1);ok('simultaneous changes accept one and reject stale version');
 let latest=race.find(r=>r.ok).current_state;
 const seen=new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{stop();reject(new Error('listener timed out'));},10000);const stop=onSnapshot(doc(operator.db,'workspaces',ws,'pallets',p.id),snap=>{if(snap.data()?.version===latest.version+1){clearTimeout(timeout);stop();resolve(snap.data());}},reject);});
 const moved=await send(owner,'move',{location_id:latest.current_location_id===a.target_id?b.target_id:a.target_id},{pallet_id:p.id,expected_version:latest.version});assert.equal(moved.ok,true);await seen;latest=moved.current_state;ok('another signed-in device receives shared changes');
 const photoId=randomUUID(),bytes=new Uint8Array([255,216,255,224,1,2,3,4]);
 const reservation=await owner.call('reservePhotoUpload',{workspaceId:ws,uploadId:photoId,bytes:bytes.length,thumbBytes:4});
 const path=reservation.full;
 await uploadBytes(ref(owner.storage,path),bytes,{contentType:'image/jpeg',customMetadata:{uploadedBy:owner.user.uid}});
 await uploadBytes(ref(owner.storage,reservation.thumb),bytes.slice(0,4),{contentType:'image/jpeg',customMetadata:{uploadedBy:owner.user.uid}});
 const photo=await owner.call('command',{...envelope('add_photo',{attachment_id:randomUUID(),data_url:`storage://${path}`,thumb_url:`storage://${reservation.thumb}`,media_type:'image/jpeg',bytes:bytes.length},{pallet_id:p.id,expected_version:latest.version}),command_id:photoId});assert.equal(photo.ok,true,JSON.stringify(photo));
 assert.equal((await getBytes(ref(operator.storage,path))).byteLength,bytes.length);assert.equal((await getBytes(ref(operator.storage,reservation.thumb))).byteLength,4);await assert.rejects(getBytes(ref(outsider.storage,path)));ok('distinct thumbnail and detail use member-only cloud storage');
 await assert.rejects(uploadBytes(ref(owner.storage,`workspaces/${ws}/photos/${owner.user.uid}/unreserved/full.jpeg`),bytes,{contentType:'image/jpeg',customMetadata:{uploadedBy:owner.user.uid}}));ok('unreserved uploads are blocked');
 await assert.rejects(getDocs(collection(owner.db,'workspaces',ws,'pallets')));ok('unbounded client collection reads are blocked');
 const removed=await send(owner,'remove_member',{user_id:operator.user.uid});assert.equal(removed.ok,true);
 await assert.rejects(getDoc(doc(operator.db,'workspaces',ws,'pallets',p.id)));await assert.rejects(send(operator,'receive',{job_id:job.target_id,description:'Blocked'}));await assert.rejects(getBytes(ref(operator.storage,path)));ok('removed teammate loses reads, writes and photos');
 const manager=await client('manager');
 await owner.call('authorizeEmail',{workspaceId:ws,email:manager.user.email,name:'Manager',role:'SUPERVISOR'});
 const futureEmail=`future-${suffix}@example.com`;
 await manager.call('authorizeEmail',{workspaceId:ws,email:futureEmail,name:'Future manager',role:'SUPERVISOR'});
 await assert.rejects(manager.call('authorizeEmail',{workspaceId:ws,email:`ownergrant-${suffix}@example.com`,name:'Forbidden',role:'OWNER'}));
 const future=await client('future');await future.call('joinAuthorizedWarehouses',{});
 assert.equal((await getDoc(doc(future.db,'workspaces',ws,'members',future.user.uid))).data().role,'SUPERVISOR');ok('manager authorizes another manager by verified email before registration');
 const cancelledEmail=`cancelled-${suffix}@example.com`;await manager.call('authorizeEmail',{workspaceId:ws,email:cancelledEmail,name:'Cancelled',role:'OPERATOR'});await manager.call('cancelAuthorization',{workspaceId:ws,email:cancelledEmail});const cancelled=await client('cancelled');await cancelled.call('joinAuthorizedWarehouses',{});await assert.rejects(getDoc(doc(cancelled.db,'workspaces',ws)));ok('cancelled authorization grants no access');
 const {db:adminDb,Timestamp}=licenseStore();
 const licenseRef=adminDb.doc(`licenses/${ws}`);
 await licenseRef.update({limits:{commandsPerUserDay:0}});
 await assert.rejects(send(owner,'receive',{job_id:job.target_id,description:'Over action quota'}),e=>e.code==='functions/resource-exhausted'&&/Existing records/.test(e.message));
 assert.equal((await getDoc(doc(owner.db,'workspaces',ws,'pallets',p.id))).exists(),true);assert.equal((await getBytes(ref(owner.storage,path))).byteLength,bytes.length);ok('action limit preserves existing records and authenticated photos');
 await licenseRef.update({limits:{maxPalletRecords:1}});await assert.rejects(send(owner,'receive',{job_id:job.target_id,description:'Over record quota'}),e=>e.code==='functions/resource-exhausted'&&/storage allowance/.test(e.message));ok('pallet storage allowance stops additions without deleting records');
 for(const limits of [{photoMonthBytes:0},{photoStoredBytes:0}]){await licenseRef.update({limits});await assert.rejects(owner.call('reservePhotoUpload',{workspaceId:ws,uploadId:randomUUID(),bytes:8,thumbBytes:4}),e=>e.code==='functions/resource-exhausted'&&/Existing photos/.test(e.message));}
 assert.equal((await getBytes(ref(owner.storage,path))).byteLength,bytes.length);await licenseRef.update({limits:{}});ok('upload and retained storage limits preserve photos and return clear errors');
 await adminDb.doc(`licenses/${ws}`).update({active:false});
 await assert.rejects(getDoc(doc(viewer.db,'workspaces',ws,'pallets',p.id)));await assert.rejects(send(owner,'receive',{job_id:job.target_id,description:'Inactive license'}));await assert.rejects(getBytes(ref(owner.storage,path)));ok('revoked license blocks reads, commands and photos');
 await adminDb.doc(`licenses/${ws}`).update({active:true,expires_at:Timestamp.fromMillis(Date.now()-1000)});await assert.rejects(send(owner,'receive',{job_id:job.target_id,description:'Expired license'}));assert.ok((await getDoc(doc(viewer.db,'workspaces',ws))).exists());
 assert.equal((await getBytes(ref(owner.storage,path))).byteLength,bytes.length);
 assert.ok((await owner.call('getWarehouseSummary',{workspaceId:ws})).counts);
 assert.ok((await owner.call('getDirectoryCounts',{workspaceId:ws,table:'jobs',ids:[job.target_id]})).values);
 assert.ok((await getDocs(query(collection(owner.db,'workspaces',ws,'events'),limit(100)))).size>0);
 await assert.rejects(owner.call('reservePhotoUpload',{workspaceId:ws,uploadId:randomUUID(),bytes:8,thumbBytes:4}));
 await assert.rejects(owner.call('authorizeEmail',{workspaceId:ws,email:'grace@example.com',name:'Grace',role:'OPERATOR'}));
 assert.equal((await owner.call('command',cmd)).current_state.id,received.current_state.id);
 ok('expired license permits member reads, photos, summaries and paginated exports during grace; blocks edits, uploads and invitations');
 await licenseRef.update({expires_at:Timestamp.fromMillis(Date.now()-15*86400000)});
 await assert.rejects(getDoc(doc(viewer.db,'workspaces',ws)));await assert.rejects(getBytes(ref(owner.storage,path)));
 ok('read-only grace ends after 14 days without deleting records');
 await licenseRef.update({expires_at:Timestamp.fromMillis(Date.now()+30*86400000)});
 assert.ok((await getDoc(doc(viewer.db,'workspaces',ws,'pallets',p.id))).exists());
 ok('renewal restores access to the same preserved records');
 await owner.call('createWarehouse',{name:'Renewed',usageKey:await issueKey(owner.user.email)});assert.equal((await getDoc(doc(owner.db,'workspaces',ws,'pallets',p.id))).exists(),true);ok('renewal restores the same warehouse and its data');
 await signOut(owner.auth);await assert.rejects(owner.call('createWarehouse',{name:'No session'}));ok('signed-out account cannot write');
 console.log(`${checks} Firebase integration checks passed.`);
} finally {await Promise.all(apps.map(deleteApp));}
