// "Does it work for my business?": honest answers for the kinds of places people ask about. Each says what
// they would track, where it lives, the word the app would use, and what Wherehouse will not do for them.
// Limits say "yet" only for things that could come later (unit counts, expiry dates, store sync); true
// non-goals (a POS, patient records, controlled substances) are stated plainly.

import type { IconName } from '../../ui/icons';

export type Fit = 'great' | 'good' | 'partial';
export type Category = 'warehouse' | 'trades' | 'makers' | 'retail' | 'auto' | 'community' | 'events' | 'other';

export interface Business {
  id: string;
  name: string;
  /** How the headline says it: "Does Wherehouse work for tire shops?" */
  say: string;
  also: string[];
  cat: Category;
  icon: IconName;
  fit: Fit;
  thing: string;
  spot: string;
  code: string;
  track: string;
  limit?: string;
}

export const CATEGORIES: { id: Category; label: string; icon: IconName }[] = [
  { id: 'warehouse', label: 'Warehouses & distribution', icon: 'building' },
  { id: 'trades', label: 'Trades & building supply', icon: 'hardhat' },
  { id: 'makers', label: 'Makers & manufacturing', icon: 'settings' },
  { id: 'retail', label: 'Stores & back rooms', icon: 'box' },
  { id: 'auto', label: 'Auto, marine & equipment', icon: 'truck' },
  { id: 'community', label: 'Schools, churches & public', icon: 'people' },
  { id: 'events', label: 'Events, venues & rentals', icon: 'calendar' },
  { id: 'other', label: 'Everything else', icon: 'sparkle' },
];

export const FIT_LABEL: Record<Fit, string> = { great: 'Great fit', good: 'Good fit', partial: 'Works, with limits' };

export const BUSINESSES: Business[] = [
  // Warehouses & distribution
  { id: 'warehouse', name: 'Small warehouse', say: 'small warehouses', also: ['warehouse', 'warehousing', 'storage', 'storage facility', 'pallet storage'], cat: 'warehouse', icon: 'building', fit: 'great', thing: 'Pallet', spot: 'Rack levels and floor lanes', code: 'A-03-02', track: 'Every pallet, the rack level it sits on, and who moved it last.' },
  { id: '3pl', name: 'Third-party logistics (3PL)', say: '3PL warehouses', also: ['3pl', 'third party logistics', 'fulfillment', 'fulfillment center', 'fulfilment', 'logistics', 'contract warehouse'], cat: 'warehouse', icon: 'stack', fit: 'good', thing: 'Pallet', spot: 'Racks, pick shelves and staging lanes', code: 'C1-04-2', track: 'Each client’s pallets and cartons kept apart, where they sit, and what shipped out for whom.', limit: 'Doesn’t invoice storage fees. It doesn’t connect to your clients’ online stores yet.' },
  { id: 'distributor', name: 'Distributor', say: 'distributors', also: ['distribution', 'distribution center', 'wholesale', 'wholesaler', 'supplier'], cat: 'warehouse', icon: 'truck', fit: 'great', thing: 'Pallet', spot: 'Racks and staging lanes', code: 'B-12-04', track: 'Incoming loads from a supplier list, where each went, and what left for which customer.' },
  { id: 'cold', name: 'Cold storage', say: 'cold storage', also: ['cold storage', 'freezer', 'freezers', 'refrigerated warehouse', 'cooler', 'frozen'], cat: 'warehouse', icon: 'database', fit: 'good', thing: 'Pallet', spot: 'Freezer and cooler racks', code: 'FZ-02-3', track: 'Pallets across freezers and coolers, so nobody stands in the cold hunting for one.', limit: 'Doesn’t log temperatures, and doesn’t track expiry dates yet.' },
  { id: 'freight', name: 'Freight or cross-dock terminal', say: 'freight terminals', also: ['freight', 'cross dock', 'cross-dock', 'crossdock', 'trucking terminal', 'terminal', 'shipping', 'ltl'], cat: 'warehouse', icon: 'swap', fit: 'great', thing: 'Pallet', spot: 'Dock doors and floor lanes', code: 'DOOR-14', track: 'Which door or lane every pallet is staged at, and which trailer it went out on.' },
  { id: 'beverage', name: 'Beer, wine or beverage distributor', say: 'beverage distributors', also: ['beverage', 'beverages', 'beer distributor', 'wine distributor', 'liquor distributor', 'soda', 'bottler', 'water delivery'], cat: 'warehouse', icon: 'pallet', fit: 'good', thing: 'Pallet', spot: 'Racks and floor lanes', code: 'BV-06-1', track: 'Pallets by brand, where they sit, and which route truck they’re loaded on.', limit: 'Doesn’t count cases or track lot and expiry dates yet.' },
  { id: 'moving', name: 'Moving and storage company', say: 'moving companies', also: ['movers', 'moving', 'moving company', 'self storage', 'vaults', 'household goods', 'relocation'], cat: 'warehouse', icon: 'truck', fit: 'great', thing: 'Crate', spot: 'Vault rows', code: 'V-07', track: 'Each customer’s crates or vaults, grouped by customer, with photos at pickup.' },
  { id: 'records', name: 'Records storage', say: 'records storage', also: ['records', 'document storage', 'file storage', 'archive', 'archives', 'records management'], cat: 'warehouse', icon: 'archive', fit: 'great', thing: 'Box', spot: 'Shelf bays', code: 'R-04-06-3', track: 'Every box with what’s inside, the shelf it’s on, and every time it was pulled.' },

  // Trades & building supply
  { id: 'lumber', name: 'Lumber yard', say: 'lumber yards', also: ['lumber', 'building supply', 'building materials', 'sawmill', 'timber', 'millwork supply'], cat: 'trades', icon: 'layers', fit: 'great', thing: 'Bundle', spot: 'Cantilever arms and yard rows', code: 'Y-02-3', track: 'Bundles and units on racks and in the yard, set aside for each contractor’s order.' },
  { id: 'contractor', name: 'General contractor', say: 'contractors', also: ['contractor', 'construction', 'builder', 'builders', 'remodeling', 'remodeler', 'home builder'], cat: 'trades', icon: 'hardhat', fit: 'great', thing: 'Pallet', spot: 'Yard and shop racks', code: 'SHOP-01', track: 'Materials staged for each project, so the crew loads the right materials for the right job.' },
  { id: 'electrical', name: 'Electrical or plumbing supply', say: 'supply houses', also: ['electrical', 'electrical supply', 'plumbing supply', 'plumbing', 'mechanical supply', 'supply house', 'wire'], cat: 'trades', icon: 'bolt', fit: 'good', thing: 'Item', spot: 'Shelves and bins', code: 'C-05-2', track: 'Wire reels, fixtures and bulk parts by shelf or bin, and orders held for pickup.', limit: 'Counts boxes and reels. It doesn’t track how many feet or pieces are left in each yet.' },
  { id: 'hvac', name: 'HVAC, plumbing or electrical contractor', say: 'HVAC and plumbing shops', also: ['hvac', 'plumber', 'plumbers', 'electrician', 'electricians', 'heating', 'air conditioning', 'service company', 'mechanical contractor'], cat: 'trades', icon: 'plug', fit: 'good', thing: 'Item', spot: 'Shop shelves and service vans', code: 'VAN-03', track: 'Equipment and parts staged for each job, and which van or shelf they’re on.', limit: 'Doesn’t dispatch techs. It doesn’t count the fittings used on each job yet.' },
  { id: 'steel', name: 'Steel or pipe supplier', say: 'steel suppliers', also: ['steel', 'pipe', 'metal', 'metals', 'metal supply', 'fabrication'], cat: 'trades', icon: 'layers', fit: 'great', thing: 'Bundle', spot: 'Long-goods racks', code: 'L-03-2', track: 'Bundles of pipe and stock on long racks, with weight limits per rack arm.' },
  { id: 'roofing', name: 'Roofing or siding contractor', say: 'roofers', also: ['roofing', 'roofer', 'roof', 'siding', 'gutters', 'exteriors', 'windows and doors'], cat: 'trades', icon: 'building', fit: 'great', thing: 'Pallet', spot: 'Yard rows and shop racks', code: 'YD-05', track: 'Pallets of shingles and siding staged for each house, and leftovers put back where they belong.' },
  { id: 'landscaping', name: 'Landscaping company', say: 'landscapers', also: ['landscaping', 'landscaper', 'lawn care', 'lawn service', 'hardscape', 'irrigation', 'snow removal', 'tree service', 'landscape supply', 'mulch', 'gravel'], cat: 'trades', icon: 'map', fit: 'good', thing: 'Item', spot: 'Yard bays, trailers and sheds', code: 'SHED-02', track: 'Mowers, trimmers, pallets of pavers and bags of seed, and which crew trailer they’re on.', limit: 'Doesn’t schedule crews or plan routes.' },
  { id: 'flooring', name: 'Flooring or tile store', say: 'flooring stores', also: ['flooring', 'tile', 'carpet', 'hardwood', 'vinyl plank', 'rugs', 'floor covering'], cat: 'trades', icon: 'grid', fit: 'great', thing: 'Item', spot: 'Roll racks and warehouse bays', code: 'RR-04-2', track: 'Carpet rolls, tile pallets and special orders waiting for install, and which customer each belongs to.' },
  { id: 'countertop', name: 'Stone or countertop fabricator', say: 'countertop shops', also: ['countertops', 'countertop', 'granite', 'quartz', 'stone', 'marble', 'slab yard', 'stone yard'], cat: 'trades', icon: 'layers', fit: 'great', thing: 'Slab', spot: 'A-frames and slab racks', code: 'AF-07', track: 'Every slab, the A-frame it leans on, photos of the veining, and which kitchen it’s reserved for.' },
  { id: 'pool', name: 'Pool and spa supply', say: 'pool supply stores', also: ['pool', 'pools', 'pool supply', 'spa', 'hot tub', 'hot tubs', 'pool service'], cat: 'trades', icon: 'target', fit: 'good', thing: 'Item', spot: 'Shelves and yard bays', code: 'P-03-1', track: 'Pumps, filters, covers and special orders, and which service truck took what.', limit: 'Counts pallets and big items. It doesn’t count single buckets on the shelf yet.' },
  { id: 'solar', name: 'Solar installer', say: 'solar installers', also: ['solar', 'solar panels', 'solar company', 'renewable', 'renewables', 'battery storage', 'ev chargers'], cat: 'trades', icon: 'sun', fit: 'great', thing: 'Pallet', spot: 'Warehouse racks and yard', code: 'SOL-02-1', track: 'Pallets of panels, inverters and racking kitted for each install, so the crew leaves with the right job.' },
  { id: 'utility', name: 'Utility or telecom yard', say: 'utility yards', also: ['utility', 'utilities', 'telecom', 'fiber', 'cable company', 'power company', 'electric co-op', 'water utility', 'broadband'], cat: 'trades', icon: 'wifi', fit: 'great', thing: 'Item', spot: 'Yard rows and laydown areas', code: 'LAY-06', track: 'Wire reels, transformers, poles and meters across the yard, and which crew pulled them.' },

  // Makers & manufacturing
  { id: 'manufacturer', name: 'Small manufacturer', say: 'small manufacturers', also: ['manufacturing', 'manufacturer', 'factory', 'machine shop', 'fabricator', 'plant', 'assembly'], cat: 'makers', icon: 'settings', fit: 'good', thing: 'Pallet', spot: 'Racks and work cells', code: 'WIP-03', track: 'Raw material and finished pallets, and where work in progress is waiting.', limit: 'Doesn’t plan production. It doesn’t count the parts used up yet.' },
  { id: 'print', name: 'Print shop', say: 'print shops', also: ['printing', 'printer', 'print shop', 'screen printing', 'promotional products', 'embroidery', 'apparel decorating'], cat: 'makers', icon: 'print', fit: 'good', thing: 'Box', spot: 'Paper racks and pickup shelves', code: 'PU-03', track: 'Paper stock by the pallet, and finished orders boxed on the pickup shelf by customer.', limit: 'Doesn’t price or schedule jobs.' },
  { id: 'brewery', name: 'Brewery, winery or distillery', say: 'breweries and wineries', also: ['brewery', 'winery', 'distillery', 'craft beer', 'cidery', 'taproom', 'meadery', 'beer', 'wine'], cat: 'makers', icon: 'database', fit: 'good', thing: 'Pallet', spot: 'Cellar racks and warehouse bays', code: 'CEL-02', track: 'Barrels, kegs and pallets of finished goods, and where each batch is aging.', limit: 'Doesn’t file tax or compliance reports. Batch and lot tracking isn’t there yet.' },
  { id: 'woodworking', name: 'Cabinet or woodworking shop', say: 'cabinet shops', also: ['cabinets', 'cabinet', 'cabinetry', 'woodworking', 'millwork', 'carpentry', 'furniture maker'], cat: 'makers', icon: 'hardhat', fit: 'good', thing: 'Part', spot: 'Sheet racks and work carts', code: 'CART-12', track: 'Sheet goods, hardware and finished boxes on carts, grouped by kitchen or job.', limit: 'Doesn’t make cut lists or drawings.' },
  { id: 'sign', name: 'Sign shop', say: 'sign shops', also: ['signs', 'signage', 'sign company', 'banners', 'wraps', 'vehicle wraps'], cat: 'makers', icon: 'flag', fit: 'good', thing: 'Item', spot: 'Material racks and install staging', code: 'INST-04', track: 'Vinyl rolls, blanks and finished signs waiting to install, and which job each is for.', limit: 'Doesn’t quote or schedule installs.' },

  // Stores & back rooms
  { id: 'furniture', name: 'Furniture store', say: 'furniture stores', also: ['furniture', 'mattress', 'mattresses', 'home goods', 'home furnishings'], cat: 'retail', icon: 'box', fit: 'great', thing: 'Item', spot: 'Back-room bays', code: 'W-02-1', track: 'Each sofa, table or mattress in the back room, and which ones are sold and waiting for delivery.' },
  { id: 'appliance', name: 'Appliance store', say: 'appliance stores', also: ['appliances', 'appliance', 'appliance dealer'], cat: 'retail', icon: 'box', fit: 'great', thing: 'Item', spot: 'Warehouse bays', code: 'B-06', track: 'Each fridge, washer or range by serial number, where it sits, and which customer it belongs to.' },
  { id: 'hardware', name: 'Hardware or farm store', say: 'hardware stores', also: ['hardware', 'hardware store', 'home improvement', 'farm store', 'feed store', 'farm and ranch'], cat: 'retail', icon: 'settings', fit: 'good', thing: 'Pallet', spot: 'Back-room racks and yard', code: 'YD-03-1', track: 'Overstock pallets, special orders held for pickup, and seasonal goods in the back.', limit: 'Sits beside your POS; it doesn’t ring sales. It doesn’t count units on the sales floor yet.' },
  { id: 'bike', name: 'Bike shop', say: 'bike shops', also: ['bike', 'bikes', 'bicycle', 'bicycles', 'cycling', 'e-bike', 'ebike', 'scooters'], cat: 'retail', icon: 'target', fit: 'good', thing: 'Bike', spot: 'Repair hooks and back-room racks', code: 'HOOK-14', track: 'Every bike in for repair, which hook it hangs on, and the parts set aside for it.', limit: 'Doesn’t write repair tickets or ring sales.' },
  { id: 'sporting', name: 'Sporting goods or outdoor store', say: 'outdoor stores', also: ['sporting goods', 'sports store', 'outdoor', 'outfitter', 'camping', 'hunting', 'fishing', 'ski shop', 'golf'], cat: 'retail', icon: 'map', fit: 'good', thing: 'Box', spot: 'Stockroom shelves and racks', code: 'SG-05-2', track: 'Overstock boxes, kayaks and bikes in the back, and rental gear coming and going.', limit: 'Tracks boxes and big items, not every pair of socks. Unit counts aren’t there yet.' },
  { id: 'music', name: 'Music store', say: 'music stores', also: ['music', 'instruments', 'guitar', 'guitar shop', 'band instruments', 'piano', 'instrument rental'], cat: 'retail', icon: 'volume', fit: 'good', thing: 'Item', spot: 'Repair room and rental racks', code: 'RENT-03', track: 'Rental instruments by serial number, who has each one, and repairs waiting for pickup.', limit: 'Doesn’t bill rental contracts.' },
  { id: 'pawn', name: 'Pawn or buy-sell shop', say: 'pawn shops', also: ['pawn', 'pawn shop', 'pawnbroker', 'buy sell', 'gold buyer', 'collectibles', 'coin shop'], cat: 'retail', icon: 'dollar', fit: 'good', thing: 'Item', spot: 'Vault shelves and back room', code: 'VLT-02-3', track: 'Every item by ticket number, which shelf it’s on, and photos from the day it came in.', limit: 'Not a pawn-loan system; it doesn’t write loans or file the required reports.' },
  { id: 'thrift', name: 'Thrift or consignment store', say: 'thrift stores', also: ['thrift', 'thrift store', 'consignment', 'resale', 'donation center', 'second hand', 'secondhand', 'vintage'], cat: 'retail', icon: 'star', fit: 'good', thing: 'Box', spot: 'Back-room shelves', code: 'S-03-4', track: 'Sorted donation boxes with what’s inside, and which shelf they’re waiting on.', limit: 'Tracks boxes and big pieces, not every single shirt on the sales floor.' },
  { id: 'bookstore', name: 'Bookstore or record shop', say: 'bookstores', also: ['books', 'bookstore', 'book store', 'used books', 'comics', 'comic shop', 'record store', 'vinyl'], cat: 'retail', icon: 'guide', fit: 'partial', thing: 'Box', spot: 'Back-room shelves', code: 'BK-02-4', track: 'Boxes of overstock, special orders and used buys waiting to be priced.', limit: 'Tracks boxes, not every single title. It doesn’t count copies yet.' },
  { id: 'retail', name: 'Retail back room', say: 'retail back rooms', also: ['store', 'shop', 'boutique', 'stockroom', 'retail', 'gift shop', 'clothing store'], cat: 'retail', icon: 'box', fit: 'good', thing: 'Box', spot: 'Stockroom shelves', code: 'BR-02-3', track: 'Overstock boxes and what’s in them, so anyone can find the extra sizes fast.', limit: 'Sits beside your register or POS; it doesn’t ring sales. It doesn’t count units sold yet.' },
  { id: 'ecommerce', name: 'Online store', say: 'online stores', also: ['ecommerce', 'e-commerce', 'online shop', 'shopify', 'amazon seller', 'etsy', 'ebay'], cat: 'retail', icon: 'send', fit: 'partial', thing: 'Bin', spot: 'Shelves and bins', code: 'P-04-2', track: 'Which bin each product lives in, so packing is faster and new hires can find products.', limit: 'Doesn’t sync with your store or count units yet. For now, use it for where products are, and your store for how many.' },

  // Auto, marine & equipment
  { id: 'tire', name: 'Tire shop', say: 'tire shops', also: ['tires', 'tire', 'tire storage', 'tire hotel', 'wheels', 'winter tires', 'seasonal storage'], cat: 'auto', icon: 'target', fit: 'great', thing: 'Set', spot: 'Tire racks', code: 'T-08-3', track: 'Seasonal tire sets stored for customers, grouped by customer, with photos.' },
  { id: 'autoparts', name: 'Auto repair or parts', say: 'auto repair shops', also: ['auto', 'auto repair', 'mechanic', 'body shop', 'collision', 'auto parts', 'garage', 'oil change'], cat: 'auto', icon: 'settings', fit: 'good', thing: 'Part', spot: 'Parts shelves', code: 'P-02-4', track: 'Parts ordered for each repair and where they’re waiting until the car comes in.', limit: 'Works beside your shop software; it doesn’t write estimates or invoices.' },
  { id: 'dealership', name: 'Car dealership', say: 'car dealerships', also: ['dealership', 'dealer', 'car dealer', 'auto dealer', 'used cars', 'car lot', 'truck dealer'], cat: 'auto', icon: 'pin', fit: 'great', thing: 'Car', spot: 'Lot rows and service bays', code: 'LOT-B-12', track: 'Where every car is parked on the lot, with photos, and who moved it last.' },
  { id: 'powersports', name: 'Motorcycle or powersports dealer', say: 'powersports dealers', also: ['motorcycle', 'motorcycles', 'atv', 'utv', 'snowmobile', 'jet ski', 'powersports', 'dirt bike', 'golf carts'], cat: 'auto', icon: 'bolt', fit: 'good', thing: 'Unit', spot: 'Showroom, back lot and parts shelves', code: 'BL-04', track: 'Every unit by VIN, where it’s parked, and the parts waiting on each repair.', limit: 'Works beside your dealer software; it doesn’t handle deals or titles.' },
  { id: 'fleet', name: 'Fleet or trucking shop', say: 'fleet shops', also: ['fleet', 'trucking', 'trucking company', 'fleet maintenance', 'transit', 'bus garage', 'school bus', 'delivery fleet'], cat: 'auto', icon: 'truck', fit: 'good', thing: 'Part', spot: 'Parts room and tire racks', code: 'PR-06-2', track: 'Parts, tires and filters on hand, and what’s set aside for each truck’s next service.', limit: 'Doesn’t schedule maintenance. It doesn’t count how many filters get used yet.' },
  { id: 'towing', name: 'Towing and impound lot', say: 'tow yards', also: ['towing', 'tow', 'tow truck', 'impound', 'impound lot', 'tow yard', 'repo', 'repossession', 'wrecker'], cat: 'auto', icon: 'lock', fit: 'great', thing: 'Vehicle', spot: 'Lot rows and spaces', code: 'IMP-C-08', track: 'Every vehicle towed in, its row and space, photos on arrival, and when it left.', limit: 'Doesn’t figure storage fees or release paperwork.' },
  { id: 'salvage', name: 'Salvage yard or auto recycler', say: 'salvage yards', also: ['salvage', 'junkyard', 'junk yard', 'auto recycler', 'auto recycling', 'scrap', 'pick and pull', 'used parts'], cat: 'auto', icon: 'refresh', fit: 'great', thing: 'Part', spot: 'Yard rows and parts racks', code: 'ROW-11', track: 'Pulled parts on racks and cars in the yard, by row, with photos.' },
  { id: 'boat', name: 'Boat or marine supply', say: 'marinas', also: ['marine', 'boat', 'boats', 'marina', 'boatyard', 'boat dealer', 'outboard'], cat: 'auto', icon: 'pin', fit: 'great', thing: 'Item', spot: 'Racks, shelves and yard', code: 'M-01-2', track: 'Engines, trailers, parts and stored gear, including what’s set aside for each boat.' },
  { id: 'rvstorage', name: 'RV and boat storage', say: 'RV storage lots', also: ['rv', 'rv storage', 'boat storage', 'camper', 'campers', 'trailer storage', 'vehicle storage', 'winter storage'], cat: 'auto', icon: 'map', fit: 'great', thing: 'Unit', spot: 'Numbered spaces and indoor bays', code: 'SP-27', track: 'Which space every RV, boat or trailer is in, whose it is, and photos at drop-off.', limit: 'Doesn’t bill monthly rent or run the gate.' },
  { id: 'equipment', name: 'Equipment rental', say: 'rental yards', also: ['rental', 'rentals', 'tool rental', 'equipment', 'equipment rental', 'heavy equipment', 'equipment dealer'], cat: 'auto', icon: 'hardhat', fit: 'great', thing: 'Unit', spot: 'Yard rows and cages', code: 'YARD-04', track: 'Every unit, where it’s parked, and who has it out.' },
  { id: 'aviation', name: 'Aviation hangar or parts', say: 'hangars', also: ['aviation', 'aircraft', 'airplane', 'hangar', 'airport', 'aircraft parts', 'fbo', 'mro', 'flight school'], cat: 'auto', icon: 'send', fit: 'partial', thing: 'Part', spot: 'Hangar shelves and cages', code: 'HGR-2-04', track: 'Parts, tooling and ground equipment, and which hangar shelf or aircraft they’re staged for.', limit: 'Doesn’t keep FAA part paperwork or airworthiness records.' },

  // Schools, churches & public
  { id: 'school', name: 'School or district', say: 'schools', also: ['school', 'schools', 'district', 'school district', 'university', 'college', 'campus', 'private school', 'preschool', 'daycare', 'child care'], cat: 'community', icon: 'people', fit: 'great', thing: 'Item', spot: 'Storage rooms and closets', code: 'GYM-02', track: 'Furniture, tech carts, sports gear and supplies across buildings and closets.' },
  { id: 'church', name: 'Church', say: 'churches', also: ['church', 'churches', 'ministry', 'worship', 'parish', 'synagogue', 'temple', 'mosque'], cat: 'community', icon: 'building', fit: 'great', thing: 'Box', spot: 'Closets and shelves', code: 'C-01-3', track: 'Holiday decorations, event supplies and outreach items, labeled by what’s inside.' },
  { id: 'library', name: 'Library', say: 'libraries', also: ['library', 'libraries', 'public library', 'library of things', 'tool library'], cat: 'community', icon: 'guide', fit: 'good', thing: 'Item', spot: 'Back rooms, closets and carts', code: 'WK-03', track: 'Laptops, hotspots, tools and event supplies that aren’t books, and who borrowed them.', limit: 'Not a catalog for books; keep your library system for those.' },
  { id: 'parks', name: 'Parks and recreation', say: 'parks departments', also: ['parks', 'parks and rec', 'parks and recreation', 'recreation', 'rec center', 'community center', 'summer camp', 'camp'], cat: 'community', icon: 'sun', fit: 'great', thing: 'Item', spot: 'Sheds, rec centers and storage rooms', code: 'SHED-04', track: 'Sports gear, tables, tents and seasonal decorations across every park and building.' },
  { id: 'city', name: 'City or county facilities', say: 'city facilities', also: ['city', 'county', 'government', 'municipal', 'municipality', 'public works', 'town', 'facilities', 'state agency'], cat: 'community', icon: 'flag', fit: 'great', thing: 'Item', spot: 'Yards, warehouses and buildings', code: 'PW-YD-2', track: 'Signs, barricades, spare parts and surplus furniture across yards and buildings.' },
  { id: 'fire', name: 'Fire department or EMS', say: 'fire departments', also: ['fire department', 'fire station', 'firehouse', 'fire', 'ems', 'ambulance', 'rescue squad', 'volunteer fire'], cat: 'community', icon: 'shield', fit: 'good', thing: 'Item', spot: 'Station storerooms and trucks', code: 'ST2-SUP', track: 'Turnout gear, hoses, spare equipment and supplies across stations and apparatus.', limit: 'Not for patient records or controlled substances.' },
  { id: 'foodbank', name: 'Food bank or pantry', say: 'food banks', also: ['food bank', 'food pantry', 'pantry', 'charity', 'nonprofit', 'non-profit', 'donations'], cat: 'community', icon: 'box', fit: 'partial', thing: 'Pallet', spot: 'Racks and floor', code: 'A-02-1', track: 'Donated pallets and where they sit, with photos and notes.', limit: 'Doesn’t track expiry dates or count cans yet. For now, use it for where your stock is.' },
  { id: 'shelter', name: 'Shelter or clothing closet', say: 'shelters', also: ['shelter', 'homeless shelter', 'clothing closet', 'clothing bank', 'diaper bank', 'mission', 'outreach', 'thrift ministry'], cat: 'community', icon: 'people', fit: 'good', thing: 'Box', spot: 'Storage rooms and shelves', code: 'CL-02-3', track: 'Donated boxes by size and kind, so volunteers find the right coats or diapers fast.', limit: 'Tracks boxes, not every single piece. It doesn’t count items yet.' },
  { id: 'league', name: 'Youth sports league or scout troop', say: 'sports leagues', also: ['league', 'little league', 'youth sports', 'soccer club', 'sports club', 'scouts', 'scout troop', 'booster club'], cat: 'community', icon: 'star', fit: 'great', thing: 'Bin', spot: 'Sheds, trailers and closets', code: 'TRL-01', track: 'Bins of balls, nets, uniforms and camping gear, and which coach or troop has them.' },
  { id: 'relief', name: 'Disaster relief or emergency management', say: 'relief teams', also: ['disaster relief', 'disaster', 'emergency management', 'relief', 'relief agency', 'emergency supplies', 'preparedness'], cat: 'community', icon: 'alert', fit: 'good', thing: 'Pallet', spot: 'Warehouses, trailers and staging sites', code: 'STG-03', track: 'Pallets of water, cots and kits, where they’re staged, and which site they went to.', limit: 'Doesn’t track expiry dates yet.' },

  // Events, venues & rentals
  { id: 'events', name: 'Event company', say: 'event companies', also: ['events', 'event', 'event planner', 'wedding', 'weddings', 'catering', 'audio visual', 'event production'], cat: 'events', icon: 'calendar', fit: 'great', thing: 'Case', spot: 'Racks and cages', code: 'E-04-1', track: 'Road cases, décor and gear, packed for each event and checked back in.' },
  { id: 'party', name: 'Party and tent rental', say: 'party rental companies', also: ['party rental', 'party rentals', 'tent rental', 'tents', 'bounce house', 'inflatables', 'linen rental', 'table and chair rental'], cat: 'events', icon: 'sparkle', fit: 'great', thing: 'Item', spot: 'Racks, bins and trailers', code: 'TENT-06', track: 'Tents, tables, chairs and linens, what’s packed for each party, and what came back.', limit: 'Doesn’t take bookings or payments.' },
  { id: 'theater', name: 'Theater or production company', say: 'theaters', also: ['theater', 'theatre', 'props', 'costumes', 'stage', 'drama', 'opera', 'dance company'], cat: 'events', icon: 'star', fit: 'great', thing: 'Prop', spot: 'Shelves, racks and bins', code: 'PROPS-03-2', track: 'Props, costumes and set pieces, and which show they’re pulled for.' },
  { id: 'studio', name: 'Photo or video studio', say: 'video studios', also: ['photography', 'photographer', 'video', 'videographer', 'studio', 'film', 'camera rental', 'production house'], cat: 'events', icon: 'camera', fit: 'great', thing: 'Kit', spot: 'Gear cages and shelves', code: 'CAGE-A-3', track: 'Camera kits, lights and grip gear, which shoot they’re out on, and who has them.' },
  { id: 'touring', name: 'Band or touring crew', say: 'touring bands', also: ['band', 'touring', 'tour', 'backline', 'musician', 'sound company', 'lighting company', 'concerts'], cat: 'events', icon: 'volume', fit: 'great', thing: 'Case', spot: 'Shop racks and trucks', code: 'TRK-2-05', track: 'Every road case, which truck it’s loaded on, and what came back after the run.' },
  { id: 'tradeshow', name: 'Trade show or exhibit house', say: 'exhibit houses', also: ['trade show', 'tradeshow', 'trade shows', 'exhibits', 'exhibit', 'booth', 'displays', 'convention'], cat: 'events', icon: 'grid', fit: 'great', thing: 'Crate', spot: 'Crate racks and warehouse bays', code: 'CR-09-1', track: 'Every booth crate, which show it’s headed to, and where it goes when it comes home.' },
  { id: 'venue', name: 'Hotel or event venue', say: 'hotels and venues', also: ['hotel', 'hotels', 'venue', 'banquet', 'resort', 'conference center', 'wedding venue', 'motel'], cat: 'events', icon: 'building', fit: 'good', thing: 'Item', spot: 'Storage rooms, back halls and closets', code: 'BQ-02', track: 'Banquet tables, chairs, AV carts and holiday décor across every storage room.', limit: 'Doesn’t book rooms or events.' },
  { id: 'museum', name: 'Museum or collection', say: 'museums', also: ['museum', 'collection', 'gallery', 'art storage', 'historical society'], cat: 'events', icon: 'image', fit: 'good', thing: 'Piece', spot: 'Storage shelves and crates', code: 'ST-02-3', track: 'Where each piece or crate is stored, with photos and every move.', limit: 'Not a full collections-management system; no accession or loan paperwork.' },

  // Everything else
  { id: 'it', name: 'IT department', say: 'IT departments', also: ['it', 'it department', 'computers', 'laptops', 'tech', 'help desk', 'data center', 'servers', 'managed services', 'msp'], cat: 'other', icon: 'keyboard', fit: 'good', thing: 'Device', spot: 'Storage rooms, cages and racks', code: 'IT-CAGE-2', track: 'Laptops, monitors and spares by asset tag, where they sit, and who has each one.', limit: 'Doesn’t manage software, licenses or device settings.' },
  { id: 'property', name: 'Property management', say: 'property managers', also: ['property management', 'property manager', 'apartments', 'landlord', 'hoa', 'facilities management', 'maintenance', 'real estate'], cat: 'other', icon: 'key', fit: 'great', thing: 'Item', spot: 'Maintenance shops and unit storage', code: 'MS-01-3', track: 'Spare appliances, filters, paint and fixtures across buildings, and which unit they went to.' },
  { id: 'auction', name: 'Auction house or estate sales', say: 'auction houses', also: ['auction', 'auctions', 'auctioneer', 'estate sale', 'estate sales', 'liquidation', 'liquidator', 'consignor'], cat: 'other', icon: 'dollar', fit: 'great', thing: 'Lot', spot: 'Floor rows and shelves', code: 'FL-06-2', track: 'Every lot, its consignor, photos, and where it sits before and after the sale.' },
  { id: 'staging', name: 'Home staging company', say: 'home stagers', also: ['home staging', 'staging', 'stager', 'interior design', 'interior designer', 'design studio'], cat: 'other', icon: 'image', fit: 'great', thing: 'Item', spot: 'Warehouse bays and shelves', code: 'ST-04-2', track: 'Every sofa, lamp and piece of art, which house it’s staged in, and what’s back on the shelf.' },
  { id: 'repair', name: 'Electronics or phone repair', say: 'repair shops', also: ['phone repair', 'computer repair', 'electronics', 'electronics repair', 'appliance repair', 'repair shop', 'tv repair'], cat: 'other', icon: 'phone', fit: 'good', thing: 'Device', spot: 'Repair shelves and bins', code: 'RP-03-2', track: 'Every device checked in, which bin it’s waiting in, and the parts ordered for it.', limit: 'Doesn’t write repair tickets or take payments.' },
  { id: 'cleaning', name: 'Cleaning or janitorial company', say: 'cleaning companies', also: ['cleaning', 'janitorial', 'custodial', 'maid service', 'commercial cleaning', 'restoration', 'carpet cleaning'], cat: 'other', icon: 'sparkle', fit: 'good', thing: 'Item', spot: 'Supply room and vans', code: 'VAN-02', track: 'Machines, carts and bulk supplies, and which van or client site they’re at.', limit: 'Doesn’t schedule crews. It doesn’t count bottles used yet.' },
  { id: 'farm', name: 'Farm or nursery', say: 'farms', also: ['farm', 'nursery', 'garden center', 'greenhouse', 'agriculture', 'ranch', 'orchard', 'florist', 'flower shop'], cat: 'other', icon: 'map', fit: 'good', thing: 'Pallet', spot: 'Barns, rows and yard', code: 'BARN-02', track: 'Pallets of feed, soil, seed and equipment across barns and yard rows.' },
  { id: 'lab', name: 'Lab or clinic storage', say: 'labs and clinics', also: ['lab', 'laboratory', 'clinic', 'medical', 'hospital', 'dental', 'research lab', 'doctors office', 'pharmacy', 'physical therapy'], cat: 'other', icon: 'lab', fit: 'partial', thing: 'Box', spot: 'Storage rooms', code: 'SR-01-2', track: 'Equipment and bulk supply boxes, and which room or shelf they’re in.', limit: 'Not for patient records or controlled substances. Lot and expiry tracking aren’t there yet.' },
  { id: 'vet', name: 'Veterinary clinic', say: 'vet clinics', also: ['vet', 'veterinary', 'veterinarian', 'animal hospital', 'animal shelter', 'animal rescue'], cat: 'other', icon: 'shield', fit: 'partial', thing: 'Box', spot: 'Storage rooms and closets', code: 'SUP-02', track: 'Bulk supplies, kennels, equipment and food pallets, and which room they’re in.', limit: 'Not for medical records or controlled drugs. Lot and expiry tracking aren’t there yet.' },
  { id: 'restaurant', name: 'Restaurant', say: 'restaurants', also: ['restaurant', 'bar', 'kitchen', 'cafe', 'coffee', 'bakery', 'commissary', 'food truck', 'caterer'], cat: 'other', icon: 'box', fit: 'partial', thing: 'Case', spot: 'Dry storage and walk-in', code: 'DRY-02', track: 'Where bulk cases and equipment are kept, especially across more than one storage room.', limit: 'Doesn’t count food or track expiry dates yet, and doesn’t order from suppliers. For now, most kitchens need a food inventory app instead.' },
];

/** The best match for whatever someone typed: a name, a synonym, or a close spelling. */
export function matchBusiness(query: string): Business | null {
  const q = query.trim().toLowerCase().replace(/[^a-z0-9 &-]/g, '');
  if (q.length < 2) return null;
  let best: { b: Business; score: number } | null = null;
  for (const b of BUSINESSES) {
    for (const term of [b.name.toLowerCase(), b.say.toLowerCase(), ...b.also]) {
      // A short alias like “it” or “bar” only counts when typed on its own, not inside “kitchen” or “barber”.
      const score = term === q ? 100 : term.startsWith(q) ? 80 : term.includes(q) || (term.length >= 4 && q.includes(term)) ? 60 : close(q, term) ? 40 : 0;
      if (score && (!best || score > best.score)) best = { b, score };
    }
  }
  return best?.b ?? null;
}

/** One typo allowed per four letters (a swapped pair counts as two). */
function close(a: string, b: string): boolean {
  if (Math.abs(a.length - b.length) > 2 || a.length < 4) return false;
  const max = Math.max(1, Math.floor(a.length / 4));
  const prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    let diag = prev[0];
    prev[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const tmp = prev[j];
      prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, diag + (a[i - 1] === b[j - 1] ? 0 : 1));
      diag = tmp;
    }
  }
  return prev[b.length] <= max;
}
