// Step-by-step task guides for the Help page. Steps use **bold** for the words printed on buttons
// and screens, so people can match them to what they see.

import type { IconName } from '../../ui/icons';
import type { HelpRole, HelpTarget } from './types';

export type TutorialGroup = 'everyday' | 'records' | 'setup';

export const TUTORIAL_GROUPS: { id: TutorialGroup; label: string; hint: string }[] = [
  { id: 'everyday', label: 'Everyday work', hint: 'Receiving, labels, moving, finding, dispatch and dead zones.' },
  { id: 'records', label: 'Keeping records right', hint: 'Damage, missing pallets, counts and corrections.' },
  { id: 'setup', label: 'Setting up', hint: 'Racks, jobs, spreadsheets, people and backups.' },
];

export interface Tutorial {
  id: string;
  group: TutorialGroup;
  icon: IconName;
  title: string;
  /** One line: what you get done. */
  outcome: string;
  minutes: number;
  /** Smallest role that can follow every step. */
  role: HelpRole;
  steps: string[];
  tip?: string;
  target: HelpTarget;
  /** The screen "Show me" opens, in words. */
  where: string;
  /** The video chapter that shows this task. */
  chapter?: string;
}

export const TUTORIALS: Tutorial[] = [
  {
    id: 'receive',
    group: 'everyday',
    icon: 'receive',
    title: 'Receive your first delivery',
    outcome: 'Give a new pallet its identity and a permanent code.',
    minutes: 2,
    role: 'OPERATOR',
    steps: [
      'Open **Receive**. On a phone it is the first tab at the bottom. On a desktop it is in the sidebar under Floor.',
      'Choose the **Job** the material belongs to, for example J-214 School renovation. Only open jobs are listed.',
      'Write a **Description** someone else would recognize: contents, packaging, color. Up to 160 characters.',
      'Add a **Supplier reference**, a **Photo** or a **Note** if they help. All three are optional.',
      'Press **Save pallet**. The server assigns the next code, like P-000031, and that code is never reused.',
      'Choose what comes next: **Place now** to put it on a rack, **Print label**, or **Receive another** for the same job.',
    ],
    tip: 'If the signal drops while saving, press **Check result**. It asks the server for the original receipt, so you never end up with a duplicate pallet.',
    target: { route: 'receive' },
    where: 'Receive',
    chapter: 'receive',
  },
  {
    id: 'labels',
    group: 'everyday',
    icon: 'print',
    title: 'Print and apply labels',
    outcome: 'Get a QR label on every pallet and rack, and keep reprints under control.',
    minutes: 3,
    role: 'VIEWER',
    steps: [
      'Right after receiving, press **Print label**. From any pallet record, the **Label** button prints it again with the same code.',
      'For a batch, open **Labels** and choose what to print: needs reprint, waiting for placement, everything on a job, a hand-picked set, or all rack labels.',
      'Press **Preview**, then print at 100 percent (actual size). The calibration square must measure exactly 1 inch.',
      'Use 4 x 6 inch thermal labels, or letter paper at six labels per page.',
      'Stick the label flat on a side that faces the aisle, so it can be scanned without moving the pallet.',
      'After a reprint, open **Reconcile**, then **Labels to reprint**, and press **New label is on** once the new one is stuck on. This step needs an Operator account or higher.',
    ],
    tip: 'The hosted preview cannot open a print dialog, so run the full app to print. The big printed code under the QR code is the fallback when a label gets damaged.',
    target: { route: 'labels' },
    where: 'Labels',
    chapter: 'labels',
  },
  {
    id: 'camera',
    group: 'everyday',
    icon: 'camera',
    title: 'Put a pallet on a rack with the phone camera',
    outcome: 'Two scans and one tap, and the record matches the rack.',
    minutes: 1,
    role: 'OPERATOR',
    steps: [
      'Open **Move**.',
      'Press **Scan with camera** and allow the camera if the phone asks.',
      'Point at the **pallet label** first. The pallet locks in as step 1.',
      'Point at the **rack label**. If you scan a rack first, the app simply asks for the pallet.',
      'Check the review card: where it was, where it is going, its job and its version.',
      'Press **Place** for a new pallet or **Move** for one already on a rack. The result says Placed or Moved only after the server saves it.',
    ],
    tip: 'No camera, or a torn label? Use **Scan from a photo**, or type the big printed code, like P-000042 or A-03-02, and press **Enter**.',
    target: { route: 'move' },
    where: 'Move',
    chapter: 'camera',
  },
  {
    id: 'putaway',
    group: 'everyday',
    icon: 'scanner',
    title: 'Put away a row of pallets with a hardware scanner',
    outcome: 'Scan one rack, then every pallet going onto it, without touching the screen.',
    minutes: 3,
    role: 'OPERATOR',
    steps: [
      'Set the scanner to keyboard mode (often called HID or keyboard-wedge mode) and to send Enter after each code. The scanner’s manual shows how. Most USB and Bluetooth scanners can do this.',
      'Open **Scanners** and scan any label to check that the portal hears the scanner.',
      'Open **Scan station** and choose **Put-away**, or scan the Put-away command barcode.',
      'Scan the **rack label** once.',
      'Scan each **pallet** going onto that rack. Each scan’s result shows on the screen as you go.',
      'Scan the **Finish** command barcode, or press Finish, and review what was saved.',
    ],
    tip: 'Keep the command barcode sheet from the Scanners page on the cart, so you can switch modes and confirm without putting the scanner down.',
    target: { route: 'station' },
    where: 'Scan station',
    chapter: 'station',
  },
  {
    id: 'find',
    group: 'everyday',
    icon: 'find',
    title: 'Find a pallet',
    outcome: 'Know where it was last confirmed, and when, in seconds.',
    minutes: 1,
    role: 'VIEWER',
    steps: [
      'Open **Find**.',
      'Type a job code (J-214), a pallet code (P-000042), a rack (A-03-02) or a few words from the description. Capitals and extra spaces do not matter.',
      'Read the location first. It shows where the pallet was **last confirmed** and when.',
      'Narrow it down with the state buttons, **On hold**, and the job and location lists.',
      'Tap a result to open the full record, with its photos, actions and history.',
    ],
    tip: 'On a keyboard, press / to jump to the search box. For everything on one job sorted by rack, open the job’s pick list in **Jobs**.',
    target: { route: 'find' },
    where: 'Find',
    chapter: 'find',
  },
  {
    id: 'dispatch',
    group: 'everyday',
    icon: 'truck',
    title: 'Dispatch a pallet to a job site',
    outcome: 'Record that material left the building, and where it went.',
    minutes: 1,
    role: 'OPERATOR',
    steps: [
      'Find the pallet. For a whole job, open **Jobs**, then the job, and work down its pick list.',
      'Check that it is **Stored** and not on hold. A held pallet cannot be dispatched until a supervisor clears the hold.',
      'On the pallet record, press **Dispatch pallet**.',
      'Check the **Destination**. It starts with the job’s destination notes. Add a note if it helps.',
      'Confirm. The pallet becomes Dispatched and its rack is cleared.',
    ],
    tip: 'A dispatch records that the pallet left, as you entered it. It is not proof the site received it. The job must be open.',
    target: { pallet: 'stored' },
    where: 'a stored pallet',
    chapter: 'dispatch',
  },
  {
    id: 'return',
    group: 'everyday',
    icon: 'returnIcon',
    title: 'Record a return',
    outcome: 'Bring material back in with the same code and its full history.',
    minutes: 1,
    role: 'OPERATOR',
    steps: [
      'Open **Find** and press the **Dispatched** filter, or search the pallet’s code.',
      'Open the pallet and press **Record return**.',
      'Add a **condition note**. If it came back damaged, add a hold reason so it cannot go out again until it is inspected.',
      'Save. The pallet is back in the building as **Received**, with the same code and history, and no rack yet.',
      'Place it with **Move**: scan the pallet, then the rack.',
    ],
    tip: 'If the job was closed in the meantime, a supervisor reopens it first. A return never clears a hold that was already on the pallet.',
    target: { route: 'find' },
    where: 'Find',
    chapter: 'dispatch',
  },
  {
    id: 'offline',
    group: 'everyday',
    icon: 'wifiOff',
    title: 'Work in a dead zone',
    outcome: 'Keep moving pallets without signal, and never lose or double a move.',
    minutes: 2,
    role: 'OPERATOR',
    steps: [
      'When the signal drops, the top bar chip says **Offline** and a banner shows when this device last had fresh records.',
      'Find and pallet records keep working from the cached copy, marked with its time.',
      'Moves and **Confirm still here** for stored pallets still work. The button reads **Queue**, and the result says Queued on this device, not confirmed.',
      'Everything else, like receiving or dispatching, waits for the connection.',
      'Back online, queued moves send themselves in order. If someone changed a pallet first, **Sync and offline** asks you to decide: move it anyway, or **Keep theirs, discard mine**.',
    ],
    tip: 'Practice safely: open **Sync and offline** and switch the network lab to **Offline (dead zone)**. The connection in this demo is simulated.',
    target: { route: 'sync' },
    where: 'Sync and offline',
    chapter: 'offline',
  },
  {
    id: 'hold',
    group: 'records',
    icon: 'hold',
    title: 'Handle damage with a hold',
    outcome: 'Stop a damaged pallet from going out until someone has looked at it.',
    minutes: 2,
    role: 'OPERATOR',
    steps: [
      'Open the damaged pallet and press **Put on hold**. Say what is wrong, for example: forklift damage, corner crushed.',
      'Move it somewhere safe, such as QUARANTINE-01, with **Move** as usual. A hold allows moves.',
      'While it is on hold it cannot be dispatched or split, and it is listed in **Reconcile** under **On hold**.',
      'A supervisor inspects it and presses **Clear hold** with what resolved it. The reason stays in the history.',
    ],
    tip: 'Operators can put a pallet on hold. Only Supervisors and Owners can clear one.',
    target: { route: 'reconcile' },
    where: 'Reconcile',
    chapter: 'holds',
  },
  {
    id: 'missing',
    group: 'records',
    icon: 'question',
    title: 'Report a missing pallet, and record where it turned up',
    outcome: 'Be honest about what is lost, without losing where it was last seen.',
    minutes: 2,
    role: 'OPERATOR',
    steps: [
      'Look around the recorded rack and the racks beside it first.',
      'Open the pallet and press **Mark missing**, with a reason such as: not at B-01-02 during the count.',
      'Its rack is cleared, the last confirmed rack is kept as history, and it is listed in **Reconcile** under **Missing**.',
      'When it turns up, a supervisor opens it, presses **Found pallet**, chooses the location where it is, and says how it was found.',
      'It is Stored there again, and the whole story is in its history.',
    ],
    tip: 'Moving a missing pallet is blocked on purpose. If an operator finds one, tell a supervisor, who records it as found.',
    target: { route: 'reconcile' },
    where: 'Reconcile',
    chapter: 'holds',
  },
  {
    id: 'count',
    group: 'records',
    icon: 'checklist',
    title: 'Run a cycle count',
    outcome: 'Check a rack against the records and fix what differs.',
    minutes: 4,
    role: 'OPERATOR',
    steps: [
      'Open **Reconcile**, then **Not verified in 3+ days**, to see which pallets to check first.',
      'Open **Scan station** and choose **Count**, or scan the Count command barcode.',
      'Scan a rack, then every pallet on it.',
      'Press or scan **Finish** to compare what you scanned with what is recorded there.',
      'Fix what differs: move pallets that were recorded somewhere else, and mark missing any that were expected but not found.',
    ],
    tip: 'On a phone you can check one pallet at a time: in **Move**, scan the pallet and the rack it is already on, then press **Confirm still here**.',
    target: { route: 'station' },
    where: 'Scan station',
    chapter: 'station',
  },
  {
    id: 'correct',
    group: 'records',
    icon: 'edit',
    title: 'Fix a mistake with a correction',
    outcome: 'Put the record right while keeping the original visible.',
    minutes: 2,
    role: 'SUPERVISOR',
    steps: [
      'Open the pallet and scroll down to **History**.',
      'Press **Correct this entry** beside the wrong entry, or **Correct the record** under More actions.',
      'Review everything that happened after that entry, so the fix matches what is really on the floor.',
      'Choose the pallet’s actual state now, and its rack if it is Stored.',
      'Give a reason and save. A new correction entry points back at the wrong one, and the original stays in the history.',
    ],
    tip: 'For a typo in the description, notes or supplier reference, **Edit details** is enough, and Operators can do it. Changing the description flags the label for reprinting.',
    target: { pallet: 'history' },
    where: 'a pallet record',
    chapter: 'corrections',
  },
  {
    id: 'setup',
    group: 'setup',
    icon: 'locations',
    title: 'Set up racks and jobs',
    outcome: 'Give every rack a label and every project a job code.',
    minutes: 5,
    role: 'SUPERVISOR',
    steps: [
      'Open **Locations** and press **New location**. Use codes like A-02-01 for zone, aisle and bay, and choose the kind: rack, receiving, quarantine, staging or floor area.',
      'Press **Rack labels** to print every rack label in one batch, and mount each one on its rack.',
      'Test a label: open **Move**, scan any pallet, then the new rack label.',
      'Open **Jobs** and press **New job**. Keep the code short, like J-240, since it prints on every label. Destination notes pre-fill dispatches.',
      'Close a job once all its material has left. It cannot close while pallets are still in the building, missing or on hold.',
    ],
    tip: 'Already have a long list in a spreadsheet? Import locations and jobs instead of typing them.',
    target: { route: 'locations' },
    where: 'Locations',
    chapter: 'locations',
  },
  {
    id: 'import',
    group: 'setup',
    icon: 'import',
    title: 'Import from a spreadsheet',
    outcome: 'Bring in racks, jobs and pallets you already track.',
    minutes: 5,
    role: 'SUPERVISOR',
    steps: [
      'Open **Import** and choose **Locations**, **Jobs** or **Pallets**. Do them in that order, since pallets need their jobs to exist.',
      'Get the template, fill it in with your spreadsheet program, and save it as CSV.',
      'Paste the CSV or press **Choose CSV file**. Up to 200 rows per batch.',
      'Read the preview. Problems are listed by row and column, so fix the file and paste it again.',
      'Press **Import**. Every row goes in, or none do. Pressing twice or losing the connection never creates duplicates, and the page warns you if the same file was imported before.',
      'Imported pallets start with no rack. Print their labels and place each one with a scan.',
    ],
    target: { route: 'import' },
    where: 'Import',
    chapter: 'csv',
  },
  {
    id: 'team',
    group: 'setup',
    icon: 'people',
    title: 'Invite your team and set roles',
    outcome: 'Give each person exactly the access their job needs.',
    minutes: 3,
    role: 'SUPERVISOR',
    steps: [
      'Open **People** and press **Invite**. Enter their name, email and role.',
      'Pick the smallest role that fits: Viewer to look, Operator for floor work, Supervisor to manage and fix, Owner for everything.',
      'Supervisors can invite Operators and Viewers. Only an Owner can grant Supervisor or Owner access.',
      'To change someone’s access, press **Role**. To take it away, press **Remove**. They lose access on their next request, and their history stays.',
      'Every change is recorded in the **Admin audit log** at the bottom of the page.',
    ],
    tip: 'Sign-in is off while we test, so an invited person is added straight away and **Sign in as** shows exactly what their role allows. Once sign-in arrives, each person will sign in with their own email.',
    target: { route: 'people' },
    where: 'People',
    chapter: 'people',
  },
  {
    id: 'backup',
    group: 'setup',
    icon: 'download',
    title: 'Back up your data',
    outcome: 'Keep your own copy of every pallet and every change.',
    minutes: 2,
    role: 'SUPERVISOR',
    steps: [
      'Open **Export**.',
      'Save each file: pallets, events (the full history), locations and jobs, plus the manifest that says when the export was made.',
      'Keep the files together in a place your company controls, in a folder named for the day you exported.',
      'Open **Data and storage** to see where records live today and what the plan is for launch.',
    ],
    tip: 'In this demo, records live only in this browser. Clearing the browser’s site data or resetting the demo removes them. In the hosted preview, Export copies each file to the clipboard instead of downloading it.',
    target: { route: 'export' },
    where: 'Export',
    chapter: 'data',
  },
];
